apiVersion: apps/v1
kind: Deployment
metadata:
  name: eol-scanner
  labels:
    app: eol-scanner
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eol-scanner
  template:
    metadata:
      labels:
        app: eol-scanner
        version: v1.0.0
    spec:
      containers:
        - name: eol-scanner
          image: eol-scanner:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: eol-scanner-secrets
                  key: api-token
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: eol-scanner-secrets
                  key: github-token
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: models-storage
              mountPath: /app/models
            - name: logs-storage
              mountPath: /app/logs
      volumes:
        - name: models-storage
          persistentVolumeClaim:
            claimName: eol-scanner-models-pvc
        - name: logs-storage
          persistentVolumeClaim:
            claimName: eol-scanner-logs-pvc
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: eol-scanner-service
  labels:
    app: eol-scanner
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: eol-scanner
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eol-scanner-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "eol-scanner-ip"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - eol-scanner.your-domain.com
      secretName: eol-scanner-tls
  rules:
    - host: eol-scanner.your-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eol-scanner-service
                port:
                  number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eol-scanner-models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eol-scanner-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: Secret
metadata:
  name: eol-scanner-secrets
type: Opaque
data:
  api-token: <base64-encoded-api-token>
  github-token: <base64-encoded-github-token>
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eol-scanner-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eol-scanner
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
