apiVersion: v1
kind: Namespace
metadata:
  name: eol-scanner
  labels:
    name: eol-scanner
    purpose: security-scanning
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: eol-scanner
  name: eol-scanner-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eol-scanner-rolebinding
  namespace: eol-scanner
subjects:
  - kind: ServiceAccount
    name: eol-scanner-sa
    namespace: eol-scanner
roleRef:
  kind: Role
  name: eol-scanner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eol-scanner-sa
  namespace: eol-scanner
